### ISSUE TITLE
New project moving along

### ISSUE THREAD

**Issue by felipealfonsog** [felipealfonsog/Upd8All#14]
Hey there ! What do you think about this new project! @PardesiCat

**Comment by PardesiCat** [comment]
Namaste, yes, I saw indeed a nice concept. I have made some suggested changes, which I explain in the pull request. 

please check my pull request https://github.com/felipealfonsog/Upd8All/pull/29

**Comment by felipealfonsog** [comment]
great! Version 0.0.17 is now up and running ... stable .... try to use the development branch please for PR ...

**Comment by felipealfonsog** [comment]
Good idea would be now to promote this utility - piece of software ...

**Comment by felipealfonsog** [comment]
Got the v.0.0.18 running better and handles better a few things .... you can get it on AUR ... yay -S upd8all 
And in this version in the tarball you appear as a contributor ! ... Thanks!

**Comment by felipealfonsog** [comment]
v.0.0.20 improved... lots of bugs and new formula now in the code ...

**Comment by PardesiCat** [comment]
Namaste... i just saw previous issue you closed.

i was busy  didnt came online 

i notice there minor issue in service script 
in both main and devlopment branch  which is 

> 
    # Extract the source file
    tar xf "v.$pkgver.tar.gz"

![ferror](https://github.com/felipealfonsog/Upd8All/assets/55957190/0d9f2b39-b178-4d6d-bf3f-c3cfe6ab16b8)


it should be

> tar -xf
  
"-" is missing   

(i see sometimes without "-" its working fine, sometimes tar error i think using tar -xf is better)

else everything working fine...

**Comment by PardesiCat** [comment]
2nd. after install succesfully

this executable file doesn't get deleted; it remains, along with install_service.sh.

![noclean](https://github.com/felipealfonsog/Upd8All/assets/55957190/8baa6013-608e-48ac-9687-eb3ff1021e32)

This was created by the following code.

> # Create a shell script to execute upd8all.py and copy it to /usr/local/bin
>     echo '#!/bin/bash' > upd8all
>     echo 'python /usr/local/bin/upd8all.py "$@"' >> upd8all
>     chmod +x upd8all
>     install -Dm755 upd8all "/usr/local/bin/upd8all"


 We should add suggested solutions inside the clean-up code.

    # Clean up temporary files
    rm -rf "v.$pkgver.tar.gz" "Upd8All-v.$pkgver"
    rm -rf "upd8all"

**Comment by felipealfonsog** [comment]
Good idea … please you’re more than welcome to create a PR …
